name: Check code quality

on:
  pull_request:
    branches:
      - master
      - develop
      - release/**

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true
      - name: Run lint
        run: |
          npm ci
          npm run lint-diff
        env:
          CI: true
          BASE: ${{ github.base_ref }}
          HEAD: ${{ github.head_ref }}
