name: Stage

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to staging server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Deploy via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          port: ${{ secrets.STAGING_SERVER_PORT }}
          username: ${{ secrets.STAGING_SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: 'dist'
          target: '/var/www'

      - name: Run shell script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          port: ${{ secrets.STAGING_SERVER_PORT }}
          username: ${{ secrets.STAGING_SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd /var/www
            bash deploy.sh
